# Generated by Django 5.2.10 on 2026-01-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('age', models.IntegerField()),
                ('hero_name', models.CharField(max_length=255)),
                ('interests', models.CharField(max_length=255)),
                ('world_setting', models.CharField(max_length=255)),
                ('education_goals', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avg_watch_time', models.FloatField()),
                ('avg_completion_rate', models.FloatField()),
                ('like_rate', models.FloatField()),
                ('share_rate', models.FloatField()),
                ('skip_rate', models.FloatField()),
                ('popularity_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_stats',
                'indexes': [models.Index(fields=['popularity_score'], name='video_stats_popular_739d89_idx'), models.Index(fields=['updated_at'], name='video_stats_updated_86a628_idx')],
            },
        ),
    ]
